- .gitignore
- agenda.php
- composer.json
- composer.lock
- credentials.json.example
- index.php
- security.php
- utils.php
- Checking that requests come from Slack (fully implemented);
- Slack url_verification (fully implemented);
- app_home_opened event detected, no filters yet (partially implemented);
- CalDAV client (partially implemented);
- synchronization of events (fully implemented);
- cleaning mechanism of old events (not implemented);
- update of events, and especially to add attendees (not implemented).
> First step

- agenda.php
- utils.php
Enhances a bit the code which deals with the agenda files
> Use shared lock for reading

- .gitignore
- agenda.php
- composer.json
- composer.lock
- index.php
- localcache.php
- slackEvents.php
- tests/FilesystemCacheTest.php
- tests/runTests.sh
- solve merging conflicts of #8 ;
- `getSerializedEvent($eventName)` added;
- removing remaining filesystem accesses in `agenda.php`.
> Decouple the agenda and the persistence code (step 2)

- .gitignore
- agenda.php
- composer.json
- composer.lock
- index.php
- localcache.php
- tests/FilesystemCacheTest.php
- tests/runTests.sh
/!\ This is still work in progress since it still misses tests on the `Agenda` class to ensure I didn't break anything /!\
However I'm already creating this PR to get early feedback (ie: if the design doesn't not look good, it would be better to know it before I go farther in this direction)
> Decouple the agenda and the persistence code

- slackEvents.php
- utils.php
- list categories;
- add a link to a open street map to locate the event;
- remove location when unspecified (ex: remote events).
> Improve user interface

- .gitignore
- CalDAVClient.php
- agenda.php
- index.php
- localcache.php
- slackAPI.php
- slackEvents.php
- tests/CalDAVTest.php
- tests/credentials.json.sample
- better handling of responses of the Slack API;
- better handling of responses from the CalDAV client;
- add some tests for `CalDAVClient.php`;
- move some parsing of CalDAV responses to `CalDAVClient.php` (instead of `agenda.php`).
Sorry, this PR is a bit messy...
> Handle errors

- agenda.php
- slackAPI.php
- slackEvents.php
- utils.php
Fix some issues (listed in the commit messages).
Feel free to ask questions if needed :)
> Some small fixes

- slack_app_manifest.yaml.sample
it will make it more convenient for other users to install this app
> Fix urls in manifest

- agenda.php
- config.json.sample
- slackEvents.php
- utils.php
Improve how mandatory categories are handled.
> Move mandatory categories into the config file

- CalDAVClient.php
- DBAgenda.php
- FSAgenda.php
- MySQLAgenda.php
- SqliteAgenda.php
- agenda.php
- config.json.sample
- header.php
same as https://github.com/Zero-Waste-Paris/slack-agenda-app/pull/44 but without the commits already cherry-picked, and with subsequent conflicts resolved
> rebased PR44

- MySQLAgenda.php
- config.json.sample
We need it to install this on our web hosting
> Mysql can use a host which is not localhost

- MySQLAgenda.php
without this patch the app doesn't handle events with UTF-8 smileys in the description
> Fix mysql encoding

- DBAgenda.php
- MySQLAgenda.php
- SqliteAgenda.php
- clitools.php
- slackAPI.php
- slackEvents.php
Allow to execute some commands from the CLI, such as:
- `php clitools.php install`;
- `php clitools.php checkAgenda`;
- `php clitools.php database create`;
- `php clitools.php api checktokens`;
- etc.
> add clitools

- .github/workflows/phplint.yml
I don't know this tool yet, but if it works as expected it should ease reviews and increase the quality of our code
(taken from https://github.com/marketplace/actions/php-lint )
> Add a PHP linter action

- MySQLAgenda.php
- SqliteAgenda.php
- agenda.php
- clitools.php
- slackEvents.php
make use of the database to store Slack reminder IDs.
> move reminders in agenda.php

- actions.php
- agenda.php
- commands.php
- slackAPI.php
- slackEvents.php
- slack_app_manifest.yaml.sample
- add the `/remindEvent` Slack command, that triggers a preview of an event (as a modal window);
- event preview in channel;
- allow registration from channel.
> Post event preview in channel

- agenda.php
Sorry about that: I missed those when I rebased and solved the conflicts of the PR #64 :-/
> Fix my mess

- clitools
With this PR it becomes possible to list all commands and to get a description of what each does
> make it possible to get help messages with clitools.php

- .github/workflows/phplint.yml
it has false positives and it won't be so useful once we have unit tests
> Rm php linter check

- utils.php
> Log rotation

- slackEvents.php
If event location contains an URL, then do not render a link to OSM.
See #78
> Remove OpenStreetMap link when event location is a link

- agenda.php
> remove `INTERSECT` from SQL commands (not available with MySQL).

- slackEvents.php
- tests/unitTests/AgendaTest.php
- tests/unitTests/MockEvent.php
- tests/unitTests/SlackEventsTest.php
- tests/unitTests/testUtils.php
this adds a test on the bug we encountered today, to ensure we'll never have regression on it.
In order to write this test a small refacto of the tests (moving some code around) was needed
> Test slack events

- .circleci/config.yml
- tests/runMysqlTests.sh
this increases the likelihood that we don't break
compatibility with this database
This fixes #85
> run mysql tests in CI

- commands.php
- config.json.sample
- header.php
- utils.php
in the short term this is useful to have a preprod bot in the
same slack as the prod one
> make slash command configurable

- agenda.php
- slackEvents.php
- utils.php
The number of attendees is wrong when there are attendees registered outside from slack (the count was always 1).
This PR fix that.
> fix: wrong number of attendees

- utils.php
It's not really clear to me why I see this error in preprod
but this patch appears to fix it
> Fix error "A non-numeric value encountered"

- MySQLAgenda.php
- SqliteAgenda.php
- agenda.php
It will be less maintenance work when when we change the
schema in the future.
> don't duplicate sql to create sql tables

- agenda.php
- slackEvents.php
- tests/unitTests/AgendaTest.php
> Display a clear message on deleted event

- agenda.php
Doing a single query is a bit better for performances.
I just tested this patch in preprod where we currently have
~30 events on the caldav server.
When I delete an event, this method runs in about 8ms without this patch
and it only takes 4ms with it.
It's admittedly not a lot since the whole query take ~0.9s, but that's
still a gain
(this relates to #63)
> Agenda.update does a bulk select

- config.json.sample
- slackEvents.php
- utils.php
>  Display something explicit when there are no event at all

- clitools
- config.json.sample
- bea6c7c71bff0c55127a23bcef1b831acf41ef5b: because I made the mistake (I have inverted the two while installing the App)...
- 08aa63a7ce76b5bc7e7593a0fa7e6ba133f08f54: to have a ready to use config file
- 95d551ab55501327e3dc8b565b97b42095406cb5: before, the check passed if the user and bot tokens were inverted
> Minor fixes

- slackAPI.php
- slackEvents.php
- slack_app_manifest.yaml.sample
> Check if the app is integrated in a channel

- tests/unitTests/SlackEventsTest.php
This test ensure we won't break this feature without
not being aware of it
> Add test for #132

- agenda.php
- tests/unitTests/AgendaTest.php
this fix was lost in a merge conflict that I did not resolved correctly
a few days ago.
(I should add a unit test to prevent such issues in the future. I don't
have time for it this evening, I'll try to do it in the next few days)
> Apply fix #129 again

- slackEvents.php
because it does not make a lot of sense to have just one
button which says "page 1" if there are no other pages
> Don't display pagination button if there is a single page

- tests/unitTests/AgendaTest.php
calling isNull() did not assert anything, the correct method call
is assertNull()
> Fix assertion for nullity

- slackAPI.php
- slackEvents.php
to make it easier to troubleshoot the error "channel_not_found"
> Conversations_members log the channelId

- slackAPI.php
- slackEvents.php
> Warn user when he or she runs /remindEvent in a private conversation

- slackEvents.php
More context on
https://github.com/Zero-Waste-Paris/slack-agenda-app/issues/59#issuecomment-1272378237
> Comment line which make the app crash

- composer.json
- composer.lock
- inc/agenda.php
- inc/slackEvents.php
- inc/utils.php
This needed to:
- update out packages
- replace a usage of a deprecated function
> Make our code compatible with PHP 8.1

- inc/agenda.php
- inc/slackEvents.php
- inc/utils.php
It turns out that date() does not care about the locale...
(from the doc https://www.php.net/manual/en/function.date.php :
> To format dates in other languages, IntlDateFormatter::format() can be used instead of date().
)
> Fix locale when printing date.

- inc/CalDAVClient.php
Now it matches its implementation
> Fix declaration of ICalDAVClient::getETags

- clitools
- inc/agenda.php
- inc/slackAPI.php
- slack_app_manifest.yaml.sample
- tests/unitTests/AgendaTest.php
Slack remove the ability for a user to schedule a reminder for another user, so we replace this by scheduled messages
(beware: I did not had the time to test it yet, I just made sure the unit tests are passing)
> Implement reminders with scheduled message

- tests/runUnitTests.sh
not sure why it did not work, but it appears that this var env needs to be set
> Fix code coverage
