Zero-Waste-Paris/slack-agenda-app

CalDAVClient.php, agenda.php, config.json.sample, index.php, slackAPI.php, utils.php
- errors are transformed as exceptions (thus the same function can handle both errors and exceptions). I discovered that: `1/0` triggers an exception (division by 0), and `$a=$b*4;` triggers an error (Undefined variable)...
- errors/exceptions are handled by `exception_handler()`;
- the content of the Slack app is replaced by a message that can be configured in `config.json`.
I have used `set_exception_handler()` and `set_error_handler()` instead of `register_shutdown_function()` because:
- the handler is called if, and only if there is an error/exception, rather than being called at each shutdown;
- `register_shutdown_function()` may fails when handling relative paths (https://stackoverflow.com/questions/13924465/shutdown-handlers-and-relative-paths).
Tell me what you think about these …
=> Add an error/exception handler

agenda.php
Users will receive emails when they register for an event. 
It is possible to decline afterwards the invitation by following a link on this email. Attendees are then tagged with `PARTSTAT=DECLINED`, but are not deleted.
This PR handle that situation.
=> Decline invitation directly from the CalDAV server

.gitattributes, README.md
The 1st commit add directives so the tarball retrieved from
https://github.com/Zero-Waste-Paris/slack-agenda-app/zipball/main won't
contain the files which are not needed to non dev users (in particular
it won't contain the tests)
The 2nd commit gives more clue to install this
=> Makes it more convenient to download tarball

slackAPI.php
I decreased it a couple days ago to avoid the noise due to false
positive, but since those false positive are now filtered out, we can
log errors as error again
=> Increase log severity on failed query to slack

slackEvents.php
Reminders are currently created at the date of the event, not 1 day before.
That's because we manipulate DateTimeImmutable (and not DateTime) so we need
to retrieve the result of the call to "modify"
=> Fix reminder date

slackEvents.php
because there are cases when those errors are expected
=> Reduce log severity when we fail to delete a reminder

slackEvents.php
Anyway the slack API call would return an error. Skipping it:
- avoid false positive in the logs
- avoid wasting latency
=> Don't try to register reminders in the past

localcache.php
I suspect that this issue is caused by this method returning NULL. This commit
will make it possible to test this hypothesis. With this additional info it will
be more convenient to understand where such inconsistent state may come from.
=> Add logging to troubleshoot #40

FSAgenda.php, agenda.php, events.php, slackEvents.php
Agenda is now an abstract class, instead of an interface.
It will prevent code duplication (as discussed in #39), between backend implementations.
=> Agenda class: from interface to abstract class

CalDAVClient.php
Otherwise when we get in the "if($httpcode !== 200 ...)" then the call
to curl_getinfo fails with error
curl_getinfo(): supplied resource is not a valid cURL handle resource
=> close CalDavClient's curl handle when we don't need it

actions.php, commands.php, events.php, slackAPI.php, utils.php
This parameter is not used because we instantiate another Logger in
the constructor
=> Rm unused parameter $log in SlackAPI constructor

MySQLAgenda.php
I'm thinking that it will likely be convenient to store the tables of
this app in an existing db (to benefit from the existing backup scripts
have and because I think we're limited in the number of db we can have
with our hosting plan), so it would be not so cool to drop the whole
database inadvertently.
=> Don't DROP DATABASE

tests/CalDAVTest.php, utils.php
Since we deleted FSAgenda this app don't write to files anymore so
- we don't use file_put_contents_safe at all
- we don't need to lock before reading a file
=> rm file_get_contents_safe and file_put_contents_safe

agenda.php, config.json.sample
because it can only be 'database' now so it's pointless.
Also it avoids that initAgendaFromType may hit no 'return' in case the db_type is unknown
=> proposition to rm conf agenda.type

MySQLAgenda.php, SqliteAgenda.php, agenda.php
with this refacto it's easier to:
- reason about the Agenda class because we don't have to look at its children
classes anymore to see where its fields are instantiated
- extend it because there are no more implied assumptions like "each child
class needs to set "$this->log" and "$this->table_prefix"
=> Proposition of a minor refacto: construct Agenda with all the data it needs

.circleci/config.yml
Our tests don't require a browser so we can use a simpler image. It's much faster to spawn it
so our CI runs are much faster with this change.
=> Speed up CI

MySQLAgenda.php, SqliteAgenda.php, agenda.php, tests/unitTests/AgendaTest.php
by default die() terminates the process with exit code 0, which is interpreted as
a success. It's annoying because consequently if a test run terminates on a die,
then the test runner will consider the test was successful (which is particularly
annoying in CI when all we care about is the exit code and we don't usually look
at the logs)
With this commit if we encounter error conditions which lead to die, the exit code
makes it clear that something bad occured
=> Don't die with 0 exit code

slackEvents.php, utils.php
prevent : `[ERROR] must be less than 76 characters` from the slack API
See: https://api.slack.com/reference/block-kit/block-elements
`A text object that defines the button's text. Can only be of type: plain_text. text may truncate with ~30 characters. Maximum length for the text in this field is 75 characters.`
=> fix: string too long for the Slack API

agenda.php
This visibility was reduced by edba60a342601662f02a3e4328b22aaf51664f04
but this method is called from slackEvent (I though I could pass it to private
because my git grep didn't find this method call because the case of the method
is different. I just learnt that PHP doesn't care about the case we use
when we call methods... :-/ )
=> Fix method visibility

agenda.php
With the current message some users thought the reminders implied
that the event was jjust about to start
This commit fixes #89
=> Enhance the message of the reminder

MySQLAgenda.php, SqliteAgenda.php, agenda.php, slackEvents.php, tests/unitTests/AgendaTest.php
This fixes #100.
The issue was that when a user register to an event which is displayed on
Slack after calling /remindEvent, then the registration is runs
`SlackEvents.more_inchannel` which doesn't call `Agenda.addReminder`.
This commit moves the creation of the reminder inside `Agenda.updateAttendee`
so every registration leads to the attempt to create a reminder.
=> All registrations may create a reminder

README.md, agenda.php
since Ubuntu LTS versions are providing PHP7 by default it seems a good idea
to support it, especially because it's (for now) easy to do
=> make this app compatible with PHP7

agenda.php, slackEvents.php, tests/unitTests/AgendaTest.php
Because slack has a limit on the number of items we can return.
It turns out that we reach this limit when we return more than 30
events.
Ideally we should add some pagination to adress this, but for now
a hard limit will avoid this issue.
(it will prevent users to see events farter in the future, but they
wouldn't be able to see it even without this limit since the app
would crash. At least with this patch they can still see the first events
and they can use category filters to see events farther in the future)
=> Limit the number of events returned

agenda.php
because of a mistake, the summary in the reminder was empty
It is a regression introduced by 16ae17abbc47adb985200e0412c4e12e80ec4bc9
(because the line
(string)$vCalendar->SUMMARY;
was moved but in the 1st context we had $vCalendar which was set to
$vCalendar = $parsed_event['vCalendar']->VEVENT;
whereas in the other it was not)
=> Fix bug in reminder creation

slackAPI.php
as explained by the comment in the method agenda.php::deleteReminder
this is not an error. However we still logged it as any generic error
in SlackAPI.
This commit adds this error in the list of errors to ignore.
=> Don't log any error when we can't find a reminder to delete

slackAPI.php
Having non UTF-8 characters is a case we may encounter if a user creates an
event with a bad encoding. And by default json_encode returns "FALSE" if it
encounters non UTF-8 characters. In such case, the call to the slack API
subsequently fails because the payload is incorrect (it has "FALSE" instead
of an expected json payload).
Adding this flag seems to make is possible to cope correctly with such bad
input
=> Be robust in case of non UTF-8 characters

CalDAVClient.php, agenda.php, tests/unitTests/MockCalDAVClient.php
Since the caldav server may be edited concurrently by several clients,
it is expected that we may get a 412 when we first try to update an event
(and we handle this case with a retry after a re-sync).
In this case it is pointless to log an error because we don't need to worry
about it.
With this patch such situation is now logged as an info.
This fixes #141
=> Don't log a 412 as an error when it is expected

slackAPI.php
it appears that in_array always returns "false" in our case.
I assume it's because it does not work well when the array
is associative.
=> Fix array parsing

slackEvents.php, tests/unitTests/utilsTest.php, utils.php
otherwise Slack displays the tags, which results
in a poor user experience
=> Ensure events are not displayed as html

inc/agenda.php, inc/slackEvents.php, tests/unitTests/AgendaTest.php
(note that this PR is built on top of #155 so it would be more convenient to review that other one before. This current PR only has 2 commits on its own)
This PR changes a bit the way we manipulate exceptions. In a nutshell it:
- favor throwing instead of returning NULL or FALSE in case of event not found (hence making the code more consistent)
- simplifies a bit the code because now `Agenda::getParsedEvent` can only return an event (instead of "an event OR a boolean") which may make it possible to propose a future refacto I have in mind)
=> Refacto exception

clitools, tests/unitTests/clitoolsTest.php
it was broken because the "require"d paths have not been adapted when I moved the files.
(in the process I replaced "require" by "require_once" so we won't
have to bother making sure we don't have double-require at any point)
This commit also adds a test to ensure this kind of bug cannot go unoticed again.
=> Fix clitools

inc/CalDAVClient.php
Otherwise parsed xml object we would get is null, which would lead to some warnings.
The most simple is probably to exit at the very beginning if we're in such case
=> Fix "null" exception

README.md, actions.php, clitools, commands.php, config.json.sample, events.php, inc/agenda.php, inc/slackAPI.php, inc/slackEvents.php, inc/utils.php, slack_app_manifest.yaml.sample, tests/unitTests/AgendaTest.php
It was only needed to create reminders, so we don't need it anymore.
Removing it simplifies a bit our code and the conf.
(Note that this PR is based on top of PR 168, which should be merged before looking at that one.)
=> Rm user token

inc/agenda.php, inc/slackAPI.php
It's not so rare that a query takes at least 1s to be handled. It's rather slow in itself, and it may be an issue since Slack has a 3s timeout (that we may fail to respect some times).
There may be ways to speed up our code (eg: caching on the filesystem some complex sql queries for which we would have the certainty that the data would remain up to date).
This commit adds some logs, and since each log it dumped with a timestamp, this should make it easier to understand where the time is going and hence where it could make sense to think of some caching system (and subsequently, if we end up developing some optimizations, it could help checking that said optimizations would actually save time)
=> Add some log in order identify our bottlenecks

inc/agenda.php
it appears to be unused since f0a9cf1962c0409b659a8ab6653a822b259f2250
=> Rm unused NotImplementedException class

.circleci/config.yml
it was left like the default conf because I did not understood it clearly back then. Now that I understand that it's actually pretty simple I simplify it.
In particular this commit:
- leverages composer.lock to compute the cache key (because we have it in our repo and it's more accurate than composer.json)
- removes the cache fallback as it would never make sense to use it in our case
=> Improve a bit CircleCI conf

.circleci/config.yml, inc/CalDAVClient.php, inc/agenda.php, tests/phpunit.xml, tests/unitTests/MockEvent.php, tests/unitTests/clitoolsTest.php
As explained on https://php.watch/versions/8.2/dynamic-properties-deprecated it is now deprecated to reference a class field which is not explicitely declared.
This PR fix this PHP8.2 incompatibility (it's the only incompatibility I'm aware of, so I guess we could migrate our prod to PHP8.2 once this is merged)
=> Fix PHP8.2 compatibility
